### ISSUE TITLE
Cheat Sheet link is broken

### ISSUE THREAD

**Issue by jgadsden** [OWASP/www-project-threat-model-cookbook#4]
The link to cheat sheet, at present it gives a 404, should probably be changed to : https://cheatsheetseries.owasp.org/cheatsheets/Threat_Modeling_Cheat_Sheet.html

**Comment by jgadsden** [comment]
Hello @jmarcil this is proposed fix in #2

**Comment by jmarcil** [comment]
#2 got auto merged at the same time as #3... but I don't see the change, will edit myself.

**Comment by jmarcil** [comment]
ok confirmed, fixed!
